import { vars, fs } from './script-utils.js';

const replaceStrings = (input, stringArrays) => {
  let processed = input;
  stringArrays.forEach((array) => {
    processed = processed.replace(array[0], array[1]);
  });
  return processed;
};

const generateSprite = () => {
  const directories = {
    source: `${vars.componentSubdir}/`,
    dest: vars.componentFileAll,
  };

  const rewriteEachIcon = (file) => {
    let processedContents = '';

    // Strip extension from file name.
    const fileSlug = file.replace('.svg', '');

    const stringSets = [
      [new RegExp(/(?:\r\n|\r|\n)/g), ''],
      [
        '<svg version="1.1" xmlns="http://www.w3.org/2000/svg"',
        `\n<symbol id="${fileSlug}"`,
      ],
      ['width="24" height="24" ', ''],
      ['<!-- Generated by IcoMoon.io -->', ''],
      ['</svg>', '\n</symbol>'],
    ];

    try {
      const contents = fs.readFileSync(directories.source + file, 'utf8');
      processedContents = replaceStrings(contents, stringSets);
    } catch (err) {
      console.error(err);
    }
    return processedContents;
  };

  const makeFile = (dir) => {
    fs.readdir(dir.source, (err, files) => {
      // Catch error.
      if (err) {
        console.log(`Unable to scan directory: ${err}`);
      }

      // Start sprite.
      let html =
        '<svg style="display:none;" xmlns="http://www.w3.org/2000/svg">';

      // Get each symbol.
      files.forEach((file) => {
        html += rewriteEachIcon(file);
      });

      // End sprite.
      html += `</svg>`;

      // Write sprite.
      fs.writeFileSync(dir.dest, html);
      console.log(`==> CAGOV: ${dir.source} ==> ${dir.dest}`);
    });
  };

  makeFile(directories);
};

export default generateSprite;
